name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r dev-requirements.txt
      - run: pylint --disable=all --enable=E make_profiler
      - run: ruff check make_profiler
